### ISSUE TITLE
AttributeError exception

### ISSUE THREAD

**Issue by adrianamor** [tejado/pokemongo-api-demo#144]
I'm getting this error when launching the script.

`
2016-07-29 17:03:46,987 [   rpc_api] [DEBUG] Error during protoc parsing - ignored.
2016-07-29 17:03:46,988 [   rpc_api] [DEBUG] Parsing sub RPC responses...
2016-07-29 17:03:46,989 [   rpc_api] [DEBUG] Parsing class: POGOProtos.Networking.Responses_pb2.GetPlayerResponse
2016-07-29 17:03:46,991 [    pgoapi] [ INFO] Cleanup of request!
Traceback (most recent call last):
  File "/spiral_poi_search.py", line 236, in <module>
    main()
  File "/spiral_poi_search.py", line 157, in main
    response_dict = api.call()
  File "/pgoapi/pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError
`

**Comment by joshk6656** [comment]
Same here.

**Comment by tejado** [comment]
Please get latest commit and try again.

**Comment by rostopira** [comment]
to get latest commit I must use "git pull"? If yes, then terminal says "Already-up-to-date" (OS X El Capitan)

**Comment by muff1225** [comment]
we have same error too.
pip installed today.
