### ISSUE TITLE
api.call() raises AttributeError in 'spiral search' example

### ISSUE THREAD

**Issue by zhirzh** [tejado/pokemongo-api-demo#147]
I downloaded the [spiral example](https://raw.githubusercontent.com/tejado/pgoapi/master/examples/spiral_poi_search.py) and ran it, but `AttributeError` was raised on `api.call()`

```
2016-07-29 19:37:01,942 [spiral_poi_search] [ INFO] Your given location: xxx
2016-07-29 19:37:01,943 [spiral_poi_search] [ INFO] lat/long/alt: xxx xxx xxx
2016-07-29 19:37:01,943 [    pgoapi] [ INFO] pgoapi v1.1.5 - Copyright (c) 2016 tjado <https://github.com/tejado>
2016-07-29 19:37:01,943 [auth_google] [ INFO] Google login for: xxx@gmail.com
2016-07-29 19:37:02,554 [auth_google] [ INFO] Google Login successful.
2016-07-29 19:37:02,554 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
2016-07-29 19:37:02,554 [    pgoapi] [ INFO] Creating a new request...
2016-07-29 19:37:02,555 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-07-29 19:37:02,555 [    pgoapi] [ INFO] Adding 'GET_HATCHED_EGGS' to RPC request
2016-07-29 19:37:02,555 [    pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC request
2016-07-29 19:37:02,555 [    pgoapi] [ INFO] Adding 'CHECK_AWARDED_BADGES' to RPC request
2016-07-29 19:37:02,556 [    pgoapi] [ INFO] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
2016-07-29 19:37:02,556 [    pgoapi] [ INFO] Execution of RPC
2016-07-29 19:37:02,807 [    pgoapi] [ INFO] Cleanup of request!
2016-07-29 19:37:02,809 [    pgoapi] [ INFO] Finished RPC login sequence (app simulation)
2016-07-29 19:37:02,809 [    pgoapi] [ INFO] Login process completed
2016-07-29 19:37:02,810 [    pgoapi] [ INFO] Creating a new direct request...
2016-07-29 19:37:02,810 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-07-29 19:37:02,810 [    pgoapi] [ INFO] Execution of RPC
2016-07-29 19:37:03,075 [    pgoapi] [ INFO] Cleanup of request!
Traceback (most recent call last):
  File "spiral_poi_search.py", line 232, in <module>
    main()
  File "spiral_poi_search.py", line 157, in main
    response_dict = api.call()
  File "/usr/local/lib/python2.7/dist-packages/pgoapi/pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError
```

**Comment by tejado** [comment]
Please get latest commit and try again.

**Comment by zxl777** [comment]
Same here.
The  latest commit : 2440a56e50b5043712b4417457e1721124a26a4d

**Comment by zhirzh** [comment]
Ok. So this is what happened. At some point in time, the "way" of calling the api methods changed.

In some earlier version, it was

``` py
api.xyz()
response = api.call()
```

now, simply calling `api.xyz()` will get you the desired response

``` py
response = api.xyz()
```

**Comment by zxl777** [comment]
Sumbit a committ to fix this problem for the examples/spiral_poi_search.py?

**Comment by zhirzh** [comment]
Well, it is not exactly a problem. The api functioning changed a while ago (don't know in which commit exactly), but the example remained the same for a while.

The example also got updated in 2440a56.

So all that is needed is to run `pip install -U git+https://github.com/tejado/pgoapi.git` to install the latest api and make appropriate changes to the code [that uses the api].

**Comment by zxl777** [comment]
Sorry, but I reported this bug just for https://github.com/tejado/pgoapi/commit/2440a56e50b5043712b4417457e1721124a26a4d

**Comment by zxl777** [comment]
Sorry, my fault. I forgot to update by
pip install -U git+https://github.com/tejado/pgoapi.git

## Now i found this problem by run the example:

 File "/usr/local/lib/python2.7/site-packages/pgoapi/rpc_api.py", line 128, in request
    raise ServerSideRequestThrottlingException("Request throttled by server... slow down man")
pgoapi.exceptions.ServerSideRequestThrottlingException: Request throttled by server... slow down man

**Comment by zhirzh** [comment]
Please read these 2 reddit posts and refer the subreddit [/r/pokemongodev](https://www.reddit.com/r/pokemongodev) in general:

[post 1](https://www.reddit.com/r/pokemongodev/comments/4v9ezj/any_current_solutions_for_the_slow_scans/d5wmofk)

[post 2](https://www.reddit.com/r/pokemongodev/comments/4va0gj/weird_issue_with_tejado_python_api/)

**Comment by zxl777** [comment]
Thank you.
