### ISSUE TITLE
spiral_poi_search.py example crashes

### ISSUE THREAD

**Issue by theRobinator** [tejado/pokemongo-api-demo#154]
Full output:

```
Robin$ python examples/spiral_poi_search.py -a ptc -u ***** -p ******* -l 'San Francisco, CA'
2016-07-30 14:13:54,057 [spiral_poi_search] [ INFO] Your given location: San Francisco, CA, USA
2016-07-30 14:13:54,058 [spiral_poi_search] [ INFO] lat/long/alt: 37.7749295 -122.4194155 0.0
2016-07-30 14:13:54,058 [    pgoapi] [ INFO] pgoapi v1.1.5 - Copyright (c) 2016 tjado <https://github.com/tejado>
2016-07-30 14:13:54,059 [  auth_ptc] [ INFO] Login for: *****
2016-07-30 14:13:55,437 [  auth_ptc] [ INFO] PTC Login successful
2016-07-30 14:13:55,437 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
2016-07-30 14:13:55,437 [    pgoapi] [ INFO] Creating a new request...
2016-07-30 14:13:55,437 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-07-30 14:13:55,438 [    pgoapi] [ INFO] Adding 'GET_HATCHED_EGGS' to RPC request
2016-07-30 14:13:55,438 [    pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC request
2016-07-30 14:13:55,438 [    pgoapi] [ INFO] Adding 'CHECK_AWARDED_BADGES' to RPC request
2016-07-30 14:13:55,438 [    pgoapi] [ INFO] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
2016-07-30 14:13:55,439 [    pgoapi] [ INFO] Execution of RPC
2016-07-30 14:13:56,739 [    pgoapi] [ INFO] Cleanup of request!
2016-07-30 14:13:56,742 [    pgoapi] [ INFO] Finished RPC login sequence (app simulation)
2016-07-30 14:13:56,743 [    pgoapi] [ INFO] Login process completed
2016-07-30 14:13:56,743 [    pgoapi] [ INFO] Creating a new direct request...
2016-07-30 14:13:56,743 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-07-30 14:13:56,744 [    pgoapi] [ INFO] Execution of RPC
2016-07-30 14:13:56,964 [    pgoapi] [ INFO] Cleanup of request!
Response dictionary: 
{   'request_id': 177432665827034882L,
    'responses': {   'GET_PLAYER': {   'player_data': {   'contact_settings': {   },
                                                          'creation_timestamp_ms': 1468982137507L,
                                                          'currencies': [   {   'name': u'POKECOIN'},
                                                                            {   'name': u'STARDUST'}],
                                                          'daily_bonus': {   },
                                                          'equipped_badge': {   },
                                                          'max_item_storage': 350,
                                                          'max_pokemon_storage': 250,
                                                          'username': u'pokeapi'},
                                       'success': True}},
    'status_code': 1}
2016-07-30 14:13:56,969 [    pgoapi] [ INFO] Creating a new direct request...
2016-07-30 14:13:56,969 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
2016-07-30 14:13:56,969 [    pgoapi] [ INFO] Execution of RPC
Traceback (most recent call last):
  File "examples/spiral_poi_search.py", line 228, in <module>
    main()
  File "examples/spiral_poi_search.py", line 159, in main
    find_poi(api, position[0], position[1])
  File "examples/spiral_poi_search.py", line 176, in find_poi
    response_dict = api.get_map_objects(latitude = util.f2i(lat), longitude = util.f2i(lng), since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "~/Projects/pokemon/pgoapi/pgoapi/pgoapi.py", line 84, in function
    return request.call()
  File "~/Projects/pokemon/pgoapi/pgoapi/pgoapi.py", line 182, in call
    response = request.request(self._api_endpoint, self._req_method_list, self.get_position())
  File "~/Projects/pokemon/pgoapi/pgoapi/rpc_api.py", line 128, in request
    raise ServerSideRequestThrottlingException("Request throttled by server... slow down man")
pgoapi.exceptions.ServerSideRequestThrottlingException: Request throttled by server... slow down man
```

**Comment by zhirzh** [comment]
Servers now implement "rate limit". So you have to wait a few moments before sending another request to the server. I find `0.6s` almost always work.

For more, please read: https://github.com/tejado/pgoapi/issues/147#issuecomment-236340298

**Comment by Eskof** [comment]
Hello,
How can we add this delay ? Thanks

**Comment by zhirzh** [comment]
SImply uncomment [line 187](https://github.com/tejado/pgoapi/blob/master/examples/spiral_poi_search.py#L187) of the example and change time (in seconds) to whatever you desire.

**Comment by Eskof** [comment]
Thanks zhirzh for this fast, and helpful answer.
I might ask something really dumb but, it doesnt show me any Pokemon, or anything, just this :

`2016-07-31 13:08:40,132 [    pgoapi] [ INFO] Creating a new direct request...
2016-07-31 13:08:40,134 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC req
uest including arguments
2016-07-31 13:08:40,134 [    pgoapi] [ INFO] Execution of RPC
2016-07-31 13:08:40,490 [    pgoapi] [ INFO] Cleanup of request!
2016-07-31 13:08:45,493 [    pgoapi] [ INFO] Creating a new direct request...
2016-07-31 13:08:45,494 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC req
uest including arguments
2016-07-31 13:08:45,496 [    pgoapi] [ INFO] Execution of RPC
2016-07-31 13:08:45,823 [    pgoapi] [ INFO] Cleanup of request!
2016-07-31 13:08:50,828 [    pgoapi] [ INFO] Creating a new direct request...
2016-07-31 13:08:50,829 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC req
uest including arguments
2016-07-31 13:08:50,831 [    pgoapi] [ INFO] Execution of RPC
2016-07-31 13:08:51,188 [    pgoapi] [ INFO] Cleanup of request!
2016-07-31 13:08:56,194 [    pgoapi] [ INFO] Creating a new direct request...
2016-07-31 13:08:56,194 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC req
uest including arguments
2016-07-31 13:08:56,196 [    pgoapi] [ INFO] Execution of RPC
2016-07-31 13:08:56,543 [    pgoapi] [ INFO] Cleanup of request!
`

**Comment by Trolldemorted** [comment]
do you also have the impression that the spotting radius has decreased?

**Comment by Eskof** [comment]
Probably, I cannot even find one pokemon (first time using it too)
Any coord I can try to show at least one working?

**Comment by zhirzh** [comment]
Please visit the subreddit [/r/pokemongodev](https://www.reddit.com/r/pokemongodev)

**Comment by Trolldemorted** [comment]
so we switch to a delay of 5s and we are fine?

**Comment by zhirzh** [comment]
@theRobinator . if you are satisfied, it would be great if you close this issue.
