### ISSUE TITLE
KeyError: 'GET_MAP_OBJECTS' in spiral search after todays API update

### ISSUE THREAD

**Issue by larsschwarz** [tejado/pokemongo-api-demo#176]
Seems like Niantic changed the MAP_OBJECTS response today ...

**Comment by genIterator** [comment]
They updated a lot on the server side, if you look on the pokemongodev reddit.
It's probably gonna take some days until the new protos are found out.
Meanwhile I am not doing any scans, so my accounts or IP does not get banned...
Here is the Protobuf issue discussion:
https://github.com/AeonLucid/POGOProtos/issues/131

**Comment by Trolldemorted** [comment]
it is not exactly a matter of the proto, but rather a bug in the pgoapi which does not send the appropriate unknown6 value to its requests.

pokemondev was pretty close to understanding the signature when they closed their discord channel, so i suppose it will not take that long until someone explains how to construct unknown6.

**Comment by tejado** [comment]
It is not really a bug but rather a part of the API that was never investigated as it worked before without it.

**Comment by Trolldemorted** [comment]
bug or missing feature, it still has to be done - please dont pull a [Mila432](https://github.com/Mila432/Pokemon_Go_API/commit/7f927e325301df1e89ed6471a095fd5ec4e38a31) on us :)

do you have access to pokemondev's discord channel?

**Comment by Vigerus** [comment]
@tejado are you going to update api soon? :)

**Comment by beeradmoore** [comment]
Project is open source @Vigerus , you can update the API.

**Comment by larsschwarz** [comment]
Kinda strange: fort_details still works, get_gym_details doesn't ...

**Comment by dnsBlah** [comment]
is there a clear fix yet?
is it actually the u6? its just a timestamp as far as i could understand between the bs posts

**Comment by larsschwarz** [comment]
Don't know, I still love to hear a quick conclusion of the change. Still wondering why they only "signed" a few requests (map object, gyms), but not others (download settings, fort details...).

**Comment by dnsBlah** [comment]
what you mean with signed? including u6?

**Comment by larsschwarz** [comment]
I don't know what u6 is used for (haven't followed all those mad discussions). Signed might be the wrong term, don't know if it's just a timestamp diff or a call that has to be done before any other calls and that validates a signature or whatever. Sorry for misusing this issue btw ... don't wanted to start another u6 discussion.

**Comment by larsschwarz** [comment]
A technical explanation: https://github.com/pkmngodev/Unknown6/issues/65

**Comment by tienthanhdhcn** [comment]
Hi , could you please let me know when the pgoapi will be updated?

**Comment by tejado** [comment]
https://github.com/keyphact/pgoapi

official pgoapi repo will be updated tomorrow.

**Comment by tienthanhdhcn** [comment]
Thank you very much @tejado. However, when I use the current pgoapi, I got the map-cell of {'s2_cell_id': 5221642796544294912L, 'current_timestamp_ms': 1470530776035L} NOT the object? What should I do with this?

**Comment by jomarocas** [comment]
i see this no exist and teh repo no exist only the user https://github.com/pkmngodev/Unknown6/issues/65

**Comment by blackhattristar** [comment]
Mines not running either. It's spitting this out in the terminal. 

`2016-08-06 20:15:08,077 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
Traceback (most recent call last):
  File "pokecli.py", line 133, in <module>
    main()
  File "pokecli.py", line 128, in main
    response_dict = api.get_map_objects(latitude =position[0], longitude = position[1], since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "/Users/creagendow/Downloads/pgoapi-master/pgoapi/pgoapi.py", line 121, in function
    return request.call()
  File "/Users/creagendow/Downloads/pgoapi-master/pgoapi/pgoapi.py", line 209, in call
    request.activate_signature(lib_path)
  File "/Users/creagendow/Downloads/pgoapi-master/pgoapi/rpc_api.py", line 82, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(encrypt.dll, 6): image not found`

Is this the same error as the one stated in this issue?

**Comment by blackhattristar** [comment]
Mine is not working either. It keeps spitting this out in the terminal:

`2016-08-06 20:15:08,077 [    pgoapi] [ INFO] Adding 'GET_MAP_OBJECTS' to RPC request including arguments
Traceback (most recent call last):
  File "pokecli.py", line 133, in <module>
    main()
  File "pokecli.py", line 128, in main
    response_dict = api.get_map_objects(latitude =position[0], longitude = position[1], since_timestamp_ms = timestamps, cell_id = cell_ids)
  File "/Users//Downloads/pgoapi-master/pgoapi/pgoapi.py", line 121, in function
    return request.call()
  File "/Users//Downloads/pgoapi-master/pgoapi/pgoapi.py", line 209, in call
    request.activate_signature(lib_path)
  File "/Users//Downloads/pgoapi-master/pgoapi/rpc_api.py", line 82, in activate_signature
    ctypes.cdll.LoadLibrary(lib_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(encrypt.dll, 6): image not found`

Is this the same error as the one stated in this issue?

**Comment by jangeja** [comment]
So I am only getting objects with
'current_timestamp_ms': 1470569750623,
's2_cell_id': 9290065149094264832

I cant see any forts or pokemon. Am I doing something wrong?

**Comment by rtw** [comment]
@jmangeja1 thats where i'm at too. any ideas?

**Comment by jangeja** [comment]
So I never tried this API before they fixed it yesterday so I don't know what the responses looked like without sending the unknown6. But I'm guessing I didn't install the python package correctly and Im not sending out unknown6 with my requests. Strange

**Comment by dnsBlah** [comment]
@jmangeja1 @rtw same here
Lets see what the update tomorrow brings as tejado already mentioned

**Comment by elliottcarlson** [comment]
@blackhattristar that is a different issue - please refer to #197 

For other issues; make sure you are using the proper updates that have not been merged in to this repo yet. Make sure you have the right dll/so for your systems architecture. Make sure you are updating your code if not just using pokecli.py to make the appropriate calls for the signature. And finally, there is now a need to [accept the TOS](https://github.com/TachyonRSA/PoGoTos/blob/master/tos.py) and mark the tutorial as complete for all accounts before they can make full calls.

**Comment by chenditc** [comment]
@elliottcarlson I tested with get_map_object call, it can be complete without accept the TOS. What do you mean by "full calls"?

**Comment by elliottcarlson** [comment]
@chenditc it won't apply to everyone - depends on if they had accepted and completed the tutorial on a real device prior or not. Make sure you have a get_player() call before get_map_object() as well.
