### ISSUE TITLE
No module named `Cryptodome`

### ISSUE THREAD

**Issue by bramstroker** [tejado/pokemongo-api-demo#189]
I did the manual installation as described in the wiki using `python setup.py install`.
The setup succeeded without any error message.
However when trying to run pokecli.py I get the following error message.
I'm running Windows 10 64-bit.

```
Traceback (most recent call last):
  File "pokecli.py", line 40, in <module>
    from pgoapi import pgoapi
  File "D:\www\pgoapi\pgoapi\__init__.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "D:\www\pgoapi\pgoapi\pgoapi.py", line 36, in <module>
    from pgoapi.auth_google import AuthGoogle
  File "D:\www\pgoapi\pgoapi\auth_google.py", line 31, in <module>
    from gpsoauth import perform_master_login, perform_oauth
  File "C:\Users\Bram\AppData\Local\Programs\Python\Python35\lib\site-packages\gpsoauth-0.3.0-py3.5.egg\gpsoauth\__init__.py", line 4, in <module>
    from . import google
  File "C:\Users\Bram\AppData\Local\Programs\Python\Python35\lib\site-packages\gpsoauth-0.3.0-py3.5.egg\gpsoauth\google.py", line 4, in <module>
    from Cryptodome.PublicKey import RSA
ImportError: No module named 'Cryptodome'
```

**Comment by ProLoDs** [comment]
well, install the requirements in the requirements.txt
`pip install -r requirements.txt`

**Comment by bramstroker** [comment]
@ProLoDs Thank you very much. Got it up and running now. Sorry for bothering with this dumb question, doing my first baby steps at Python atm.
