### ISSUE TITLE
No Module named google.protobuf

### ISSUE THREAD

**Issue by kashtrip** [tejado/pokemongo-api-demo#19]
Hi, I am getting the following error. What am I doing wrong?

```
python main.py --debug -u tejado -p 1234 --location "New York, Washington Square"
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import pokemon_pb2
  File "C:\Users\Akash\Downloads\pokemongo-api-demo-master\pokemongo-api-demo-master\pokemon_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
ImportError: No module named google.protobuf
```

**Comment by jbaiter** [comment]
You have to install the protobuf package:

```
pip install protobuf
```

**Comment by kashtrip** [comment]
That worked. Thanks

**Comment by Simon0x** [comment]
Use python 2.7 not the 3.5 
Tryed first with python 3.5 but this only make problem.
