### ISSUE TITLE
AttributeError on pgoapi.py

### ISSUE THREAD

**Issue by r3pek** [tejado/pokemongo-api-demo#203]
This must be a dumb error 'cause i didn't see anyone complaining about it...

```
2016-08-08 17:37:43,035 [      MainThread][        models][    INFO] Connecting to local SQLite database
2016-08-08 17:37:43,037 [   search_thread][        search][    INFO] Search overseer starting
2016-08-08 17:37:43,037 [   search_thread][        search][    INFO] Starting search worker threads
2016-08-08 17:37:43,038 [   search_thread][        search][    INFO] New location caught, moving search grid
2016-08-08 17:37:43,039 [ search_worker_0][        search][    INFO] Search step 1 beginning (queue size is 36)
2016-08-08 17:37:43,039 [ search_worker_0][        search][   ERROR] Exception in search_worker: 
Traceback (most recent call last):
  File "/opt/pokemon-go-map/pogom/search.py", line 219, in search_worker_thread
    check_login(args, account, api, step_location)
  File "/opt/pokemon-go-map/pogom/search.py", line 266, in check_login
    api.set_authentication(provider = account['auth_service'], username = account['username'], password = account['password'])
  File "/usr/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 89, in getattr
    raise AttributeError
AttributeError

```

but can i get some help with this error? thx

**Comment by elliottcarlson** [comment]
`set_authentication` is a method in the new code; but when not available it tries to find it as a call to the API which does not exist and raises that error - are you using the right version of the library?

**Comment by r3pek** [comment]
@elliottcarlson i'm using the master version of this repo..... and version 2.2.0 of pokemongo-map

EDIT: old-demo works fine

**Comment by deevusone** [comment]
I have the same error too.. i followed the install instructions thoroughly.. however, the only issue was the map.  https://github.com/AHAAAAAAA/PokemonGo-Map.git doesn't have the files anymore, so i had to d/l the development map that was in the video tutorial.  Can someone pls help us resolve this issue?

**Comment by deevusone** [comment]
pip install -r requirements.txt --upgrade
npm install

the above solved the issue.
