### ISSUE TITLE
AttributeError on pgoapi.py

### ISSUE THREAD

**Issue by kkd** [tejado/pokemongo-api-demo#207]
This code worked fine on v1.1.0. After upgrading to v1.1.6, it can't work.
It may login successfully, but failed execution of RPC 'sfida_action_log'.

it may be simillar to #203.

Code(near api call):

```
    api = PGoApi()
    api.set_position(XXX, -XXX, 0.0)
    if not api.login('google', 'XXX', 'XXXX'):
        logging.debug("Login Failed!")
        return

    api.sfida_action_log()
    response = api.call()
       (...)
```

Debug Log:

```
2016-08-09 05:51:28,759 [    pgoapi] [ INFO] pgoapi v1.1.6 - Copyright (c) 2016 tjado <https://github.com/tejado>
2016-08-09 05:51:28,759 [    pgoapi] [DEBUG] Set Position - Lat: XXX Long: -XXX Alt: 0.0
2016-08-09 05:51:28,759 [    pgoapi] [DEBUG] Auth provider: google
2016-08-09 05:51:28,760 [auth_google] [ INFO] Google login for: XXXX
2016-08-09 05:51:29,409 [auth_google] [ INFO] Google Login successful.
2016-08-09 05:51:29,409 [auth_google] [DEBUG] Google Session Token: XXXXX
2016-08-09 05:51:29,409 [    pgoapi] [ INFO] Starting RPC login sequence (app simulation)
2016-08-09 05:51:29,409 [    pgoapi] [ INFO] Creating a new request...
2016-08-09 05:51:29,409 [    pgoapi] [ INFO] Adding 'GET_PLAYER' to RPC request
2016-08-09 05:51:29,410 [    pgoapi] [ INFO] Adding 'GET_HATCHED_EGGS' to RPC request
2016-08-09 05:51:29,410 [    pgoapi] [ INFO] Adding 'GET_INVENTORY' to RPC request
2016-08-09 05:51:29,410 [    pgoapi] [ INFO] Adding 'CHECK_AWARDED_BADGES' to RPC request
2016-08-09 05:51:29,410 [    pgoapi] [ INFO] Adding 'DOWNLOAD_SETTINGS' to RPC request including arguments
2016-08-09 05:51:29,410 [    pgoapi] [DEBUG] Arguments of 'DOWNLOAD_SETTINGS': 
2016-08-09 05:51:29,410 [   rpc_api] [DEBUG] Generated new random RPC Request id: 994305415477766272
2016-08-09 05:51:29,411 [    pgoapi] [ INFO] Execution of RPC
2016-08-09 05:51:29,411 [   rpc_api] [DEBUG] Generating main RPC request...
2016-08-09 05:51:29,411 [   rpc_api] [DEBUG] Incremented RPC Request ID: 994305415477766273
2016-08-09 05:51:29,411 [   rpc_api] [DEBUG] NO auth ticket found - using oauth token
2016-08-09 05:51:29,411 [   rpc_api] [DEBUG] Generating sub RPC requests...
2016-08-09 05:51:29,475 [   rpc_api] [DEBUG] Subrequest class: POGOProtos.Networking.Requests.Messages_pb2.DownloadSettingsMessage
2016-08-09 05:51:29,475 [   rpc_api] [DEBUG] Generated protobuf request: 
(...)
2016-08-09 05:51:29,477 [   rpc_api] [DEBUG] Execution of RPC
2016-08-09 05:51:29,995 [   rpc_api] [DEBUG] Parsing main RPC response...
2016-08-09 05:51:29,995 [   rpc_api] [DEBUG] Protobuf structure of rpc response:
(...)
2016-08-09 05:51:30,010 [   rpc_api] [DEBUG] Parsing sub RPC responses...
2016-08-09 05:51:30,010 [   rpc_api] [DEBUG] Parsing class: POGOProtos.Networking.Responses_pb2.GetPlayerResponse
2016-08-09 05:51:30,094 [   rpc_api] [DEBUG] Received auth ticket valid for 00:29:59 hours (1470689490094 < 1470691289875)
2016-08-09 05:51:30,094 [    pgoapi] [ INFO] Cleanup of request!
2016-08-09 05:51:30,101 [    pgoapi] [DEBUG] Setting API endpoint to: https://pgorelease.nianticlabs.com/plfe/253/rpc
2016-08-09 05:51:30,101 [    pgoapi] [ INFO] Finished RPC login sequence (app simulation)
2016-08-09 05:51:30,101 [    pgoapi] [ INFO] Login process completed
2016-08-09 05:51:30,101 [    pgoapi] [ INFO] Creating a new direct request...
2016-08-09 05:51:30,101 [    pgoapi] [ INFO] Adding 'SFIDA_ACTION_LOG' to RPC request
2016-08-09 05:51:30,102 [    pgoapi] [ INFO] Execution of RPC
2016-08-09 05:51:30,102 [   rpc_api] [DEBUG] Generating main RPC request...
2016-08-09 05:51:30,102 [   rpc_api] [DEBUG] Incremented RPC Request ID: XXXXX
2016-08-09 05:51:30,102 [      auth] [DEBUG] Auth ticket still valid for further 00:29:59 hours (1470689490103 < 1470691289875)
2016-08-09 05:51:30,102 [   rpc_api] [DEBUG] Found auth ticket - using this instead of oauth token
2016-08-09 05:51:30,102 [   rpc_api] [DEBUG] Generating sub RPC requests...
2016-08-09 05:51:30,102 [   rpc_api] [DEBUG] Generated protobuf request: 
(...)
unknown12: 989
2016-08-09 05:51:30,103 [   rpc_api] [DEBUG] Execution of RPC
2016-08-09 05:51:30,518 [   rpc_api] [DEBUG] Parsing main RPC response...
2016-08-09 05:51:30,518 [   rpc_api] [DEBUG] Protobuf structure of rpc response:
(...)

2016-08-09 05:51:30,532 [   rpc_api] [DEBUG] Decode raw over protoc (protoc has to be in your PATH):
(...)

2016-08-09 05:51:30,532 [   rpc_api] [DEBUG] Parsing sub RPC responses...
2016-08-09 05:51:30,533 [   rpc_api] [DEBUG] Parsing class: POGOProtos.Networking.Responses_pb2.SfidaActionLogResponse
2016-08-09 05:51:30,544 [    pgoapi] [ INFO] Cleanup of request!
Traceback (most recent call last):
  File "pokeroute.py", line 268, in <module>
    main()
  File "pokeroute.py", line 202, in main
    response = api.call()
  File "/Users/takeshi/workspaces/pokeroute/ve/lib/python3.5/site-packages/pgoapi/pgoapi.py", line 89, in __getattr__
    raise AttributeError
AttributeError

```

**Comment by kkd** [comment]
I removed **api.call()** and api.sfida_action_log() directly, so it worked fine.
So I fixed this ticket.
