### ISSUE TITLE
AttributeError after api.activate_signature("./encrypt.so")

### ISSUE THREAD

**Issue by malebelk** [tejado/pokemongo-api-demo#216]
I installed Ubuntu 16.04, pip, git.

Run 

> pip.exe install  git+https://github.com/tejado/pgoapi.git

and get this error

> Traceback (most recent call last):
>   File "/home/pro/createscanspot/createspot.py", line 50, in <module>
>     main()
>   File "/home/pro/createscanspot/createspot.py", line 10, in main
>     api.activate_signature("./encrypt.so")
>   File "/home/pro/.local/lib/python2.7/site-packages/pgoapi/pgoapi.py", line 89, in **getattr**
>     raise AttributeError
> AttributeError

```
from pgoapi.protos.POGOProtos.Networking.Requests_pb2 import RequestType


#print RequestType.keys()
for a in RequestType.keys():
    print a
```

METHOD_UNSET
PLAYER_UPDATE
GET_PLAYER
GET_INVENTORY
DOWNLOAD_SETTINGS
DOWNLOAD_ITEM_TEMPLATES
DOWNLOAD_REMOTE_CONFIG_VERSION
FORT_SEARCH
ENCOUNTER
CATCH_POKEMON
FORT_DETAILS
ITEM_USE
GET_MAP_OBJECTS
FORT_DEPLOY_POKEMON
FORT_RECALL_POKEMON
RELEASE_POKEMON
USE_ITEM_POTION
USE_ITEM_CAPTURE
USE_ITEM_FLEE
USE_ITEM_REVIVE
TRADE_SEARCH
TRADE_OFFER
TRADE_RESPONSE
TRADE_RESULT
GET_PLAYER_PROFILE
GET_ITEM_PACK
BUY_ITEM_PACK
BUY_GEM_PACK
EVOLVE_POKEMON
GET_HATCHED_EGGS
ENCOUNTER_TUTORIAL_COMPLETE
LEVEL_UP_REWARDS
CHECK_AWARDED_BADGES
USE_ITEM_GYM
GET_GYM_DETAILS
START_GYM_BATTLE
ATTACK_GYM
RECYCLE_INVENTORY_ITEM
COLLECT_DAILY_BONUS
USE_ITEM_XP_BOOST
USE_ITEM_EGG_INCUBATOR
USE_INCENSE
GET_INCENSE_POKEMON
INCENSE_ENCOUNTER
ADD_FORT_MODIFIER
DISK_ENCOUNTER
COLLECT_DAILY_DEFENDER_BONUS
UPGRADE_POKEMON
SET_FAVORITE_POKEMON
NICKNAME_POKEMON
EQUIP_BADGE
SET_CONTACT_SETTINGS
GET_ASSET_DIGEST
GET_DOWNLOAD_URLS
GET_SUGGESTED_CODENAMES
CHECK_CODENAME_AVAILABLE
CLAIM_CODENAME
SET_AVATAR
SET_PLAYER_TEAM
MARK_TUTORIAL_COMPLETE
LOAD_SPAWN_POINTS
ECHO
DEBUG_UPDATE_INVENTORY
DEBUG_DELETE_PLAYER
SFIDA_REGISTRATION
SFIDA_ACTION_LOG
SFIDA_CERTIFICATION
SFIDA_UPDATE
SFIDA_ACTION
SFIDA_DOWSER
SFIDA_CAPTURE

What can be wrong?

**Comment by riyadfebrian** [comment]
i have the same problem...
